apiVersion: "cis.f5.com/v1"
kind: TransportServer
metadata:
  labels:
    f5cr: "true"
  name: svc1-tcp-transport-server
  namespace: monitoring
spec:
  virtualServerAddress: "192.168.101.101"
  virtualServerPort: 9090
  virtualServerName: prometheus-1
  mode: standard
  snat: auto
  pool:
    service: prometheus-service
    servicePort: 9090
    monitor:
      type: tcp
      interval: 10
      timeout: 10
