apiVersion: "cis.f5.com/v1"
kind: IngressLink
metadata:
  name: vs-ingresslink
  namespace: nginx-ingress
spec:
  virtualServerAddress: "192.168.101.101"
  iRules:
    - /Common/Shared/Proxy_Protocol_iRule
  selector:
    matchLabels:
      app: nginx-ingress
